apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: skillpulse-prod

labels:
- pairs:
    env: prod

resources:
- ../../base
- ingress.yaml

patches:
- patch: |-
    - op: replace
      path: /spec/replicas
      value: 3
  target:
    kind: Rollout
    name: backend


images:
- name: backend
  newName: shettymalathi113/skillpulse-backend
  newTag: 1290c3610bede90c54b7cb34d858381fe8ec6e0b
- name: frontend
  newName: shettymalathi113/skillpulse-frontend
  newTag: 1290c3610bede90c54b7cb34d858381fe8ec6e0b
- name: shettymalathi113/skillpulse-backend
  newName: shettymalathi113/skillpulse-backend
  newTag: e98b107eb413f249e0df9e149524ea738e66159a
- name: shettymalathi113/skillpulse-frontend
  newName: shettymalathi113/skillpulse-frontend
  newTag: e98b107eb413f249e0df9e149524ea738e66159a
