apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: skillpulse-prod

resources:
- ../../base
- ingress.yaml

patches:
- patch: |-
    - op: replace
      path: /spec/replicas
      value: 3
  target:
    kind: Deployment
    name: backend
images:
- name: backend
  newName: shettymalathi113/skillpulse-backend
  newTag: 84a6ecbef28398bc637dfb13fd8647e123348d04
- name: frontend
  newName: shettymalathi113/skillpulse-frontend
  newTag: 84a6ecbef28398bc637dfb13fd8647e123348d04
