apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: skillpulse-prod

resources:
- ../../base
- ingress.yaml

patches:
- patch: |-
    - op: replace
      path: /spec/replicas
      value: 3
  target:
    kind: Deployment
    name: backend
images:
- name: backend
  newName: shettymalathi113/skillpulse-backend
  newTag: 7aff93c4b5c9edbdb9a745738aa65bc6224be8c3
- name: frontend
  newName: shettymalathi113/skillpulse-frontend
  newTag: 7aff93c4b5c9edbdb9a745738aa65bc6224be8c3
