# =========================================
# FRONTEND DEPLOYMENT
# =========================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend

spec:
  replicas: 1

  selector:
    matchLabels:
      app: frontend

  template:
    metadata:
      labels:
        app: frontend

    spec:
      containers:
        - name: frontend
          image: skillpulse-frontend

          ports:
            - containerPort: 80

---
# =========================================
# FRONTEND SERVICE
# =========================================
apiVersion: v1
kind: Service
metadata:
  name: frontend

spec:
  type: ClusterIP

  selector:
    app: frontend

  ports:
    - port: 80
      targetPort: 80

---
# =========================================
# BACKEND ROLLOUT
# =========================================
apiVersion: argoproj.io/v1alpha1
kind: Rollout

metadata:
  name: backend
  labels:
    app: backend

spec:
  replicas: 1

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      containers:
        - name: backend
          image: skillpulse-backend

          ports:
            - containerPort: 8080

          env:
            - name: DB_HOST
              value: mysql

            - name: DB_PORT
              value: "3306"

            - name: PORT
              value: "8080"

            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: skillpulse-db
                  key: MYSQL_USER

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: skillpulse-db
                  key: MYSQL_PASSWORD

            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: skillpulse-db
                  key: MYSQL_DATABASE

  strategy:
    canary:
      steps:
        - setWeight: 20
        - pause:
            duration: 30s

        - setWeight: 50
        - pause:
            duration: 30s

        - setWeight: 100

---
# =========================================
# BACKEND SERVICE
# =========================================
apiVersion: v1
kind: Service
metadata:
  name: backend

spec:
  type: ClusterIP

  selector:
    app: backend

  ports:
    - port: 8080
      targetPort: 8080
