# k8s/aiops/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aiops-ui
  labels:
    app: aiops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aiops
  template:
    metadata:
      labels:
        app: aiops
    spec:
      containers:
      - name: aiops
        image: your-docker-image:latest
        ports:
        - containerPort: 8090
apiVersion: v1
kind: Service
metadata:
  name: aiops-ui
spec:
  selector:
    app: aiops
  type: LoadBalancer
  ports:
    - port: 8090
      targetPort: 8090
