apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: default
  namespace: argocd
spec:
  description: Default project for SkillPulse
  sourceRepos:
    - "https://github.com/malathi-shetty/github-actions-kubernetes-masterclass.git"
  destinations:
    - namespace: skillpulse
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
