apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: skillpulse-prod
  labels:
    app: frontend
    env: prod
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: skillpulse-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: shettymalathi113/skillpulse-frontend:latest
          ports:
            - containerPort: 80
