apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: skillpulse-dev

labels:
  - pairs:
      env: dev

resources:
  - ../../base

images:
  - name: skillpulse-backend
    newName: shettymalathi113/skillpulse-backend
    newTag: latest

  - name: skillpulse-frontend
    newName: shettymalathi113/skillpulse-frontend
    newTag: latest

patches:
  - target:
      kind: Rollout
      name: backend
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
